version: '3'
services:
  mysql:
    image: mysql:8.0.17
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gin_test
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306

  # mysql_helper:
  #   build:
  #     context: .
  #     dockerfile: ./docker/mysql_helper/Dockerfile
  #   container_name: mysql_helper
  #   command: ./init.sh
  #   volumes:
  #     - ./docker/mysql_helper:/app
  #   depends_on:
  #     - mysql

  # front:
  #   build:
  #     context: .
  #     dockerfile: ./docker/front/Dockerfile
  #   hostname: front
  #   volumes:
  #     - node_modules:/app/node_modules:cached
  #   ports:
  #     - '3000:3000'

  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    environment:
      - ENV=test
    ports:
      - '8080:8080'
    tty: true
    volumes:
      - .:/go/src/app
    command: fresh
    depends_on:
      - mysql

volumes:
  db:
    driver: local
