apiVersion: v1
kind: Service
metadata:
  name: mysql-master
  labels:
    app: mysql-master
spec:
  ports:
  - port: 3306
  selector:
    app: mysql-master
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: ssd
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-master
spec:
  selector:
    matchLabels:
      app: mysql-master
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-master
    spec:
      containers:
      - image: gin-mysql
        name: mysql-master
        imagePullPolicy: Never # for local docker image
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
          # valueFrom:
          #   secretKeyRef:
          #     name: dbsecret
          #     key: root_password
        # - name: MYSQL_USER
        #   valueFrom:
        #     secretKeyRef:
        #       name: dbsecret
        #       key: user
        # - name: MYSQL_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: dbsecret
        #       key: password
        ports:
        - containerPort: 3306
          name: mysql-master
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim