apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "learnmemo.fullname" . }}
  labels:
    {{- include "learnmemo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "learnmemo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "learnmemo.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "learnmemo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: nginx
          image: gihyodocker/nginx:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          env:
          - name: WORKER_PROCESSES
            value: "2"
          - name: WORKER_CONNECTIONS
            value: "1024"
          - name: LOG_STDOUT
            value: "true"
          - name: BACKEND_HOST
            value: "localhost:8080"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: DB_HOST
            value: mysql
          - name: DB_NAME
            value: gin
          - name: DB_USER
            value: root
          - name: DB_PASSWORD
            value: password
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
