version: '3'

services:
  mysql:
    image: mysql:8.0.17
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gin
      # MYSQL_USER: root
      # MYSQL_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
#    - ./db/data:/var/lib/mysql
    - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
#    - ./db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306
