name: Deploy

on:
  push:
    branches:
      - fix/deploy_action

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
         node-version: '12'
         check-latest: true
      - name: frontend build
        run: yarn install
        working-directory: ./frontend
      - name: frontend build
        run: yarn build
        working-directory: ./frontend
      - uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "learnmemo"
          heroku_email: "koishimst@gmail.com"
          usedocker: true
